# Generated by Django 3.0.6 on 2020-05-27 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTrucks',
            fields=[
                ('truckID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('avatarSRC', models.TextField()),
                ('avatarALT', models.CharField(max_length=20)),
                ('avatarTitle', models.CharField(max_length=20)),
                ('coverPhotoSRC', models.TextField()),
                ('coverPhotoAlt', models.CharField(max_length=20)),
                ('coverPhotoTitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('speedOfService', models.IntegerField()),
                ('qualityAndTaste', models.IntegerField()),
                ('valueForMoney', models.IntegerField()),
                ('comment', models.TextField(max_length=128)),
                ('truckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckReviews.FoodTrucks')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
