# Generated by Django 3.0.6 on 2020-05-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0003_auto_20200527_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtrucks',
            name='avatarALT',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='avatarSRC',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='avatarTitle',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='coverPhotoALT',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='coverPhotoSRC',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='coverPhotoTitle',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='facebook',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='instagram',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='twitter',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='foodtrucks',
            name='website',
            field=models.TextField(default=None),
        ),
    ]
