# Generated by Django 3.0.6 on 2020-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0004_auto_20200527_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtrucks',
            name='facebook',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
