# Generated by Django 3.0.6 on 2020-06-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0005_auto_20200527_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtrucks',
            old_name='truckID',
            new_name='truck',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewID',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='truckID',
            new_name='truck',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userID',
            new_name='user',
        ),
    ]
