# Generated by Django 3.0.6 on 2020-06-03 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0006_auto_20200603_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('truck', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('avatar_alt_text', models.CharField(blank=True, max_length=20)),
                ('avatar_title', models.CharField(blank=True, max_length=20)),
                ('cover_photo_url', models.URLField(blank=True)),
                ('cover_photo_alt_text', models.CharField(default='No photo provided', max_length=20)),
                ('cover_photo_title', models.CharField(default='No photo provided', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=30)),
                ('twitter', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='datePosted',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='qualityAndTaste',
            new_name='quality_and_taste',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='speedOfService',
            new_name='speed_of_service',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='valueForMoney',
            new_name='value_for_money',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='truck',
        ),
        migrations.AddField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='FoodTrucks',
        ),
        migrations.AddField(
            model_name='review',
            name='food_truck',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='truckReviews.FoodTruck'),
        ),
    ]
