# Generated by Django 3.0.6 on 2020-06-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0007_auto_20200604_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
