# Generated by Django 3.0.6 on 2020-06-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0008_auto_20200604_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='speed_of_service',
            field=models.IntegerField(choices=[(1, 'Positive'), (0, 'Neutral'), (-1, 'Negative')]),
        ),
    ]
