# Generated by Django 3.0.6 on 2020-06-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0010_auto_20200613_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
