# Generated by Django 3.0.6 on 2020-06-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckReviews', '0012_auto_20200613_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(blank=True, default='category', max_length=20),
        ),
    ]
